spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2309
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        default_schema: bankdemo
      javax:
        persistence:
          create-database-schemas: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-circular-references: true
        
server:
  port: 8080
  servlet:
    context-path: /bankdemo
  tomcat:
    redirect-context-root: false

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
      base-path: /actuator
  info:
    env:
      enabled: true
      
info:
  author: Ivan Ryabov
  name: Boot Demo
  description: Spring Boot Security Data
  
bean:
  service-impl:
    account: accountServiceJPA
    bill: billServiceJPA
    operation: operationServiceJPA
  